theme: jekyll-theme-minimal
title: Konstantinos Kallas
introduction: I am a computer engineering student at the National Technical University of Athens. I enjoy studying about programming languages and developing software.

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num"