theme: jekyll-theme-minimal
title: Konstantinos Kallas
introduction: I am an computer engineering student at National Technical University of Athens. I enjoy studying about programming languages and developing software.   

plugins:
  - jekyll-last-modified-at